// Generated by scripts/export-abis.mjs — do not edit by hand.
// Re-run `pnpm abis` after changing MarketFactory's external interface.

export const marketFactoryAbi = [
  {
    "type": "function",
    "name": "createMarket",
    "inputs": [
      {
        "name": "base",
        "type": "address",
        "internalType": "address"
      },
      {
        "name": "quote",
        "type": "address",
        "internalType": "address"
      },
      {
        "name": "owner",
        "type": "address",
        "internalType": "address"
      },
      {
        "name": "maxChangePerSecond",
        "type": "uint256",
        "internalType": "uint256"
      },
      {
        "name": "delay",
        "type": "uint64",
        "internalType": "uint64"
      },
      {
        "name": "maxStepElapsed",
        "type": "uint64",
        "internalType": "uint64"
      },
      {
        "name": "window",
        "type": "uint64",
        "internalType": "uint64"
      }
    ],
    "outputs": [
      {
        "name": "amm",
        "type": "address",
        "internalType": "contract ConditionalAmm"
      },
      {
        "name": "oracle",
        "type": "address",
        "internalType": "contract LaggedTwapOracle"
      }
    ],
    "stateMutability": "nonpayable"
  },
  {
    "type": "event",
    "name": "MarketCreated",
    "inputs": [
      {
        "name": "amm",
        "type": "address",
        "indexed": true,
        "internalType": "address"
      },
      {
        "name": "oracle",
        "type": "address",
        "indexed": true,
        "internalType": "address"
      },
      {
        "name": "base",
        "type": "address",
        "indexed": false,
        "internalType": "address"
      },
      {
        "name": "quote",
        "type": "address",
        "indexed": false,
        "internalType": "address"
      }
    ],
    "anonymous": false
  }
] as const;
