#!/usr/bin/env node
/**
 * Copies the ABIs a consumer actually needs out of Foundry's build output and
 * into `packages/chain`, as TypeScript with `as const` so callers get full type
 * inference from viem or wagmi.
 *
 * Foundry's `out/` is gitignored and rebuilt constantly, so anything outside the
 * contracts package that reaches into it will break the first time someone
 * clones the repo and has not run `forge build`. Exporting deliberately gives
 * the frontend a stable, committed surface.
 *
 *   node scripts/export-abis.mjs
 *
 * Re-run after changing any contract's external interface. `pnpm abis:check`
 * fails if the committed copies have drifted.
 */

import { mkdirSync, readFileSync, writeFileSync, existsSync } from "node:fs";
import { join, dirname } from "node:path";
import { fileURLToPath } from "node:url";

const root = join(dirname(fileURLToPath(import.meta.url)), "..");
const OUT = join(root, "packages/contracts/out");
const DEST = join(root, "packages/chain/src/abis");

/** Contract → the artifact directory Foundry wrote it to. */
const CONTRACTS = {
  FutarchyGovernor: "FutarchyGovernor.sol",
  FutarchyExecutor: "FutarchyExecutor.sol",
  MarketFactory: "MarketFactory.sol",
  ConditionalVault: "ConditionalVault.sol",
  ConditionalToken: "ConditionalToken.sol",
  ConditionalAmm: "ConditionalAmm.sol",
  LaggedTwapOracle: "LaggedTwapOracle.sol",
};

const check = process.argv.includes("--check");

function render(name, abi) {
  return (
    `// Generated by scripts/export-abis.mjs — do not edit by hand.\n` +
    `// Re-run \`pnpm abis\` after changing ${name}'s external interface.\n\n` +
    `export const ${name.charAt(0).toLowerCase() + name.slice(1)}Abi = ${JSON.stringify(abi, null, 2)} as const;\n`
  );
}

function main() {
  if (!existsSync(OUT)) {
    console.error("No build output. Run `forge build --root packages/contracts` first.");
    process.exit(1);
  }

  mkdirSync(DEST, { recursive: true });
  const written = [];
  let drifted = 0;

  for (const [name, dir] of Object.entries(CONTRACTS)) {
    const artifact = join(OUT, dir, `${name}.json`);
    if (!existsSync(artifact)) {
      console.error(`FAIL  missing artifact for ${name} (${artifact})`);
      process.exit(1);
    }

    const { abi } = JSON.parse(readFileSync(artifact, "utf8"));
    const body = render(name, abi);
    const target = join(DEST, `${name}.ts`);

    const existing = existsSync(target) ? readFileSync(target, "utf8") : null;
    if (existing !== body) {
      drifted++;
      if (!check) writeFileSync(target, body);
    }

    written.push(name);
    const events = abi.filter((f) => f.type === "event").length;
    const fns = abi.filter((f) => f.type === "function").length;
    console.log(`ok    ${name.padEnd(20)} ${String(fns).padStart(3)} fns, ${String(events).padStart(2)} events`);
  }

  const index =
    `// Generated by scripts/export-abis.mjs — do not edit by hand.\n\n` +
    written
      .map((n) => `export { ${n.charAt(0).toLowerCase() + n.slice(1)}Abi } from "./${n}.js";`)
      .join("\n") +
    "\n";
  const indexPath = join(DEST, "index.ts");
  const existingIndex = existsSync(indexPath) ? readFileSync(indexPath, "utf8") : null;
  if (existingIndex !== index) {
    drifted++;
    if (!check) writeFileSync(indexPath, index);
  }

  console.log("");
  if (check && drifted > 0) {
    console.error(`${drifted} file(s) out of date. Run \`pnpm abis\` and commit the result.`);
    process.exit(1);
  }
  console.log(check ? "ABIs are up to date." : `Exported ${written.length} ABIs to packages/chain/src/abis/`);
}

main();
